version: "0.2"
language: en
caseSensitive: false
allowCompoundWords: false
useGitignore: true
ignorePaths:
  - "**/{cspell.*,cSpell.*,.cspell.*,cspell.config.*}"
  - "**/node_modules/**"
  - "**/build/**"
  - "**/dist/**"
  - "**/.vscode/**"
  - pnpm-lock.yaml
  - package-lock.json
  - "*.svg"
words:
  - Adafruit
  - ADNS-5050
  - ADNS-9800
  - ASUS
  - autoplay
  - AVRDUDESS
  - badjeff
  - Ballz
  - bancouver
  - BCHJJ
  - Bluetosis
  - Bouni
  - Caterina
  - cgxkb
  - CL05A105KA5NQNC
  - Consolas
  - Daughterboard
  - Deskthority
  - digi-key
  - EEPROM
  - ergosnm
  - Freerouting
  - frontmatter
  - Fuyu
  - geoah
  - Haptick
  - HATSU
  - inorichi
  - JLCPCB
  - joric
  - Kailh
  - Keebfolio
  - keyball
  - keycaps
  - keymap
  - keymaps
  - Keyplus
  - kicad
  - Manuform
  - MDBT
  - Menlo
  - Miao
  - mikoto
  - Miniboard
  - MISUMI
  - MOSI
  - mousekeys
  - MSYS
  - noto
  - nvmrc
  - PCBA
  - pcbs
  - peaceiris
  - Pinmap
  - Ploopy
  - praescriptos
  - SCLK
  - SDIO
  - sidera
  - siderakb
  - Skeletyl
  - SOIC
  - Spacemouse
  - Sphale
  - SPST
  - SUDU
  - Taobao
  - trackbowl
  - Trackpad
  - transibunt
  - trentrand
  - TRRS
  - UART
  - UEFI
  - VBUS
  - VDDIO
  - victorlucachi
  - W25Q128JVSIQ
  - Zazu
  - zite
